language: go

go:
  - "1.12.x"
  - master

script:
  - export GO111MODULE=on
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)